### ISSUE TITLE
Commit & Push History

### ISSUE THREAD

**Issue by jrshelby** [HHSAPCompSci2020/capstone-project-group-12-ks#2]
Hi group!
I am seeing some issues in your commit history that I'm going to ask you to think about. Right now, I see:
- No commits from some group members
- No commits within the week

To ensure that you get credit for your work, please make sure you are committing and pushing frequently and that each group member commits and pushes their own code.

**Comment by SJoshi910** [comment]
Sorry about that, Kinjal and I committed all the work we forgot to commit and I who had fewer commits also committed my current work so that I would receive credit.
